version: '3'
#https://www.youtube.com/watch?v=VFIt8uxug6s
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: example
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/mti_app
    ports:
      - '80:8000'
    depends_on:
      - db