# Generated by Django 4.1.3 on 2022-11-16 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('cod_area', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.SmallIntegerField(choices=[(1, 'Registrado'), (2, 'En espera'), (3, 'En proceso'), (4, 'Atendiendo'), (5, 'Cancelado')], default=1)),
                ('comment_estado', models.TextField(blank=True, max_length=120)),
                ('fecha_estado', models.DateField(auto_now_add=True)),
                ('hora_estado', models.TimeField(auto_now_add=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('area', models.ManyToManyField(blank=True, to='myapp.area')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, max_length=120)),
                ('lugar', models.CharField(max_length=50)),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('hora_solicitud', models.TimeField(auto_now_add=True)),
                ('registo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.registroticket')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='ticket',
            field=models.ManyToManyField(blank=True, to='myapp.ticket'),
        ),
    ]
