# Generated by Django 4.1.3 on 2022-11-16 16:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0003_remove_ticket_registo_ticket_registo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegistroTicket',
            new_name='Registro',
        ),
    ]
