# Generated by Django 4.1.3 on 2022-11-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_registroticket_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='registo',
            field=models.ManyToManyField(blank=True, to='myapp.registro'),
        ),
    ]
