# Generated by Django 4.1.3 on 2022-11-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_ticket_registo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='completado',
            field=models.BooleanField(default=False),
        ),
    ]
