# Generated by Django 4.1.3 on 2022-11-16 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_ticket_completado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='registo',
            new_name='registro',
        ),
    ]
