# Generated by Django 4.1.3 on 2022-11-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_registo_ticket_registro'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadosTicket',
            fields=[
                ('estado', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=20)),
            ],
        ),
    ]
