# Generated by Django 4.1.3 on 2022-11-16 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_estadosticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.estadosticket'),
        ),
    ]
