# Generated by Django 4.1.3 on 2022-11-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_registro_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='siglas',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
