# Generated by Django 4.1.3 on 2022-11-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_area_siglas'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='fecha_cierre',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='hora_cierre',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
